# Custom Prompt
format = '''$all'''

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '❯(bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [custom.buid-os]
# command = "echo $'🖥️ ($env.BUILD_OS)'"
# when = '$env.BUILD_OS'

# [custom.buid-arch]
# command = "echo $'⛩️ ($env.BUILD_ARCH)'"
# when = '$env.BUILD_ARCH'

# [custom.buid-type]
# command = "echo $'🐞 ($env.BUILD_TYPE)'"
# when = '$env.BUILD_TYPE'
