# Custom Prompt
format = """
$username\
$container\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$sudo\
$cmd_duration\
$status\
$line_break\
$time\
$shell\
@ \
"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[env_var.BUILD_OS]
variable = "BUILD_OS"
format = "$symbol [$env_value]($style) "
symbol = "🖥️"
style = "bold yellow"
default = ""

[env_var.BUILD_ARCH]
variable = "BUILD_ARCH"
format = "$symbol [$env_value]($style) "
symbol = "⛩️"
style = "bold yellow"
default = ""

[env_var.CMAKE_BUILD_TYPE]
variable = "CMAKE_BUILD_TYPE"
format = "$symbol [$env_value]($style) "
symbol = "🐞"
style = "bold yellow"
default = ""

[hostname]
ssh_only = false

[container]
format = '[$name]($style) on '	

[os]
disabled = false

[status]
symbol = ''
success_symbol = ''
format = '[\[$symbol$signal_name$int\]]($style) '
map_symbol = true
disabled = false
